$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Definition
Write-Host "Starting master installation..."
Write-Host "Step 1: Python"
& "$SCRIPT_DIR\install_python.ps1"
Write-Host "Step 2: Git"
& "$SCRIPT_DIR\install_git.ps1"
Write-Host "Step 3: Aider"
& "$SCRIPT_DIR\install_aider.ps1"
Write-Host "Step 4: Ollama"
& "$SCRIPT_DIR\install_ollama.ps1"
Write-Host "Step 5: Ollama models"
& "$SCRIPT_DIR\install_ollama_models.ps1"
Write-Host "Step 6: VS Code"
& "$SCRIPT_DIR\install_vscode.ps1"
Write-Host "Step 7: VS Code Aider extension"
& "$SCRIPT_DIR\install_vscode_aider_extension.ps1"
Write-Host "All installations completed successfully."
